# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en"
reviews:
  profile: chill
  auto_review:
    enabled: false
  review_status: false
  poem: false
chat:
  auto_reply: false
